### ISSUE TITLE
TipTap Rich Text Editor List and Table Styles Broken

### ISSUE THREAD

**Issue by artemchs** [songkeys/tailwind-preset-mantine#8]
## Description
When using the Mantine TipTap rich text editor (installed according to the official documentation at https://mantine.dev/x/tiptap/), there are rendering issues with lists and tables when Tailwind and tailwind-preset-mantine are present in the project. These elements render correctly when Mantine is used standalone without Tailwind.

### Current Behavior
- List bullets and numbers are not visible
- Table borders are not rendered
- All other rich text editor functionality works as expected

![Screenshot 2024-11-17 122857](https://github.com/user-attachments/assets/1c25cb03-8fe3-4135-b00f-2ec9228f2b4b)

### Expected Behavior
- List bullets and numbers should be visible for both unordered and ordered lists
- Table borders should be rendered properly

![Screenshot 2024-11-17 122925](https://github.com/user-attachments/assets/02b5b226-d440-4dff-90af-74e485d4c448)

### Steps to Reproduce
1. Install Mantine TipTap following the official documentation
2. Set up a basic rich text editor implementation
3. Create a list (ordered or unordered)
4. Create a table
5. Observe that list markers and table borders are missing

## Technical Details
- **Environment**:
  - "@mantine/core": "^7.13.4"
  - "@mantine/tiptap": "^7.14.1"
  - "react": "^18.3.1"
  - "tailwind-preset-mantine": "^1.2.1"
  - "tailwindcss": "^3.4.14"

## Possible Cause
The issue appears to be related to style conflicts between Tailwind's CSS and Mantine's TipTap styles. When Tailwind is removed, the components render correctly, indicating a CSS specificity or override issue.

## Additional Notes
This issue specifically affects the visual rendering of elements and does not impact the functional behavior of the editor. The HTML structure is correct, but the styles are not being applied as expected.

**Comment by songkeys** [comment]
<img width="515" alt="SCR-20241117-rtyw" src="https://github.com/user-attachments/assets/ad6bfd71-da0c-46dd-9308-477bb07d29c0">

The reason for this is that Mantine Tiptap doesn't come with default styles for lists and tables. As a result, the list bullets and numbers, for instance, follow the browser's default styling.

The `tw_base` style we imported has removed all of the browser's default styles, allowing for easier customization and a more consistent appearance across different browsers. Because of this, you won't see any styling for these undefined elements.

To address this, I recommend defining these styles yourself in globals.css:

```css
// globals.css

ul {
  list-style: disc;
}

ol {
  list-style: decimal;
}

// ...
```

Alternatively, a more practical solution might be to request that Mantine provide these styles so that others could also benefit from this.

**Comment by artemchs** [comment]
Thanks!
